In [3]:
import numpy as np


In [4]:
np.array(5)

array(5)

In [5]:
np.array([1,2,3,4,])

array([1, 2, 3, 4])

In [11]:
np.arange(1,51,).reshape(5,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [8]:
np.array([[1,2],[2,3]],dtype="float64")

array([[1., 2.],
       [2., 3.]])

In [16]:
np.array([[[[1,2],[6,8]],[[9,6],[5,9]]]])

array([[[[1, 2],
         [6, 8]],

        [[9, 6],
         [5, 9]]]])

In [18]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [24]:
a.reshape(2,3,4).ones((2,2))

AttributeError: 'numpy.ndarray' object has no attribute 'ones'

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.ones_like(a.reshape(2,3,4))

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [38]:
np.full(6,0)

array([0, 0, 0, 0, 0, 0])

In [39]:
np.full_like(a,30)

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
       30, 30, 30, 30, 30, 30, 30])

In [54]:
np.random.rand(2,6)

array([[0.60228067, 0.83328687, 0.78384254, 0.78665187, 0.06961858,
        0.01139999],
       [0.41097193, 0.3687805 , 0.47809685, 0.92023039, 0.79898341,
        0.11152044]])

In [55]:
import matplotlib.pyplot as plt

In [57]:
x = np.linspace(1,10,100)
y = np.cos(x)
print(x)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [62]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [65]:
aa =[1,2,3]
bb = aa
aa=[12]
bb

[1, 2, 3]

In [66]:
employees_data = np.array([['kelly', 'Randall', 'Jennifer', 'fteven', 'Anna', 'Roger', 'Katrina', 'Andrew', 'feborah', 'Kristy', 'jennifer', 'Jeffrey', 'Lauren', 'Nicholas', 'jeggy', 'Brian', 'Connie', 'Corey', 'derek', 'brittany', 'John', 'amanda', 'Kylie', 'Eddie', 'peter'],
['Manning', 'martin', 'Roman', 'Jones', 'Brooks', 'fitzgerald', 'Ho', 'Rodriguez', 'fstes', 'Norris', 'Castro', 'Harper', 'Mendoza', 'mahoney', 'Kelley', 'Rodgers', 'Flores', 'Sharp', 'jimmons', 'Graham', 'Woods', 'Rose', 'Johnson', 'white', 'Acevedo'],
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],   
[5339.26, 3553.56, 3914.35, 5403.55, 3664.38, 4955.78, 2678.91, 5269.36, 2793.79, 3246.82, 3436.11, 3681.08, 4509.77, 5325.75, 7875.65, 4394.52, 3864.65, 5371.3, 2741.29, 3779.03, 2603.61, 7256.27, 4279.48, 6890.37, 4630.28], 
['M', 'F', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F', 'M', 'M', 'F', 'F', 'M', 'F', 'M', 'F', 'F', 'M', 'M', 'F', 'M', 'F', 'F'],
[2, 3, 3, 4, 1, 0, 0, 0, 4, 0, 2, 4, 5, 3, 4, 4, 4, 5, 2, 1, 4, 0, 3, 5, 3] ,
[0, 2, 4, 0, 15, 5, 12, 4, 19, 0, 18, 12, 12, 16, 20, 15, 8, 7, 0, 19, 7, 20, 12, 12, 10]])


customers_data = np.array([['Jeremy', 'Shelby', 'Barbara', 'Stephen', 'Paige', 'Deborah', 'Erin', 'Kelly', 'Tyler', 'Susan', 'Tyler', 'Alexandra', 'Jerry', 'Roy', 'Nancy', 'Marc', 'Scott', 'Clayton', 'Angela', 'Timothy', 'Aaron', 'Ariana', 'Patrick', 'Amy', 'Steven'],
['Gray', 'Smith', 'Lambert', 'Martinez', 'Jefferson', 'Kelly', 'Stephenson', 'Dixon', 'Hunt', 'Robbins', 'Jennings', 'Parsons', 'Rogers', 'Patrick', 'Graham', 'Terrell', 'Patterson', 'Freeman', 'Willis', 'Hall', 'Green', 'Fields', 'Delacruz', 'Ward', 'Coleman'],
[1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025],
[6, 22, 22, 22, 21, 25, 4, 11, 11, 6, 11, 6, 19, 1, 7, 3, 13, 25, 16, 9, 17, 19, 6, 6, 7],
['2023-08-24', '2023-12-29', '2023-05-04', '2024-02-07', '2024-03-12', '2024-04-08', '2023-10-17', '2024-03-01', '2023-10-11', '2024-03-26', '2023-11-02', '2023-10-06', '2023-05-28', '2023-10-14', '2024-04-11', '2024-03-12', '2023-09-24', '2024-02-20', '2024-03-31', '2024-01-27', '2023-09-20', '2023-04-29', '2024-03-07', '2023-07-16', '2024-04-06'],
[256.51, 339.17, 110.21, 641.82, 586.05, 655.87, 772.61, 248.58, 781.33, 509.9, 931.28, 370.67, 773.07, 178.61, 896.05, 696.03, 142.34, 559.21, 124.89, 119.31, 407.55, 712.07, 298.42, 294.59, 685.43]])

In [73]:
employees_data[:,4]

array(['Anna', 'Brooks', '5', '3664.38', 'M', '1', '15'], dtype='<U32')

In [76]:
customers_data[[0],[1]]

array(['Shelby'], dtype='<U32')